version: '3.3'

services:
  postgres_server:
    build: ./postgreServer
    restart: always
    env_file:
      - ./postgreServer/config/postgres.env
    networks:
      - dockercompose

  dotnet_api:
    build: ./teste_docker_api
    restart: always
    depends_on:
      - postgres_server
    ports:
      - "5022:8080"
    networks:
      - dockercompose

networks:
  dockercompose:
    driver: bridge